Update test_pytest_with_redefine.yml

diff --git a/.github/workflows/test_pytest_with_redefine.yml b/.github/workflows/test_pytest_with_redefine.yml
--- a/.github/workflows/test_pytest_with_redefine.yml
+++ b/.github/workflows/test_pytest_with_redefine.yml
@@ -44,3 +44,17 @@ jobs:
           /tmp/redefine_installation
           pytest -sv || true
           cat /tmp/coyote.log
+          if [ ! -z $(grep "Dune client Sending data" "/tmp/coyote.log") ]; 
+          then
+            echo "success. coyote sent to dune";
+          elsed
+            echo "coyote failed. check logs"
+            exit 1
+          fi
+          if [ ! -z $(grep "Failed sending git changes to Dune" "/tmp/coyote.log") ]; 
+          then
+            echo "coyote failed to send to dune. check logs"
+            exit 1
+          else
+            echo "success. coyote sent to dune";
+          fi
